import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { transform } from 'esbuild';

const root = 'integrations/solar-system-atlas/src/';
const app = await readFile(root + 'App.tsx', 'utf8');
const main = await readFile(root + 'main.tsx', 'utf8');
const css = await readFile('src/styles/heritage-preview.css', 'utf8');
assert.match(app, /const uiPreview = 'heritage'/);
assert.match(app, /data-ui-preview=\{uiPreview\}/);
assert.ok(main.indexOf('heritage-preview.css') > main.indexOf('mobile-ui.css'));

const selectors = [...css.replace(/\/\*[\s\S]*?\*\//g, '').matchAll(/([^{}]+)\{/g)].map(m => m[1].trim());
for (const selector of selectors.filter(s => !s.startsWith('@') && !['from', 'to'].includes(s))) {
  assert.ok(selector.startsWith('.atlas'), selector);
  assert.ok(selector.includes('[data-ui-preview=heritage]'), selector);
}
assert.ok(!css.includes('var(--serif)'), 'Use existing, defined typography tokens');
assert.ok(!/\.(canvas-layer|label-layer|holo-layer)|--app-height:|--panel-w:/.test(css), 'Scene and mobile geometry remain unchanged');
assert.match(css, /scroll-margin-top:140px/);
assert.match(css, /align-items:center;justify-content:center/);
assert.match(css, /archive-rail\.archive-rail/);
const result = await transform(css, { loader: 'css', minify: true });
assert.match(css, /archive-rail__list\s*\{\s*display:flex;flex-direction:column;gap:8px/);
assert.match(css, /archive-rail__list\s*\{flex-direction:row;gap:8px/);
assert.match(app, /data-ui-motion=\{uiMotion\}/);
assert.match(css, /prefers-reduced-motion:no-preference/);
assert.match(css, /\[data-ui-motion=full\]/);
assert.ok(!/transition:all|animation:[^;\n]*infinite/.test(css));
assert.ok(selectors.filter(s => s.startsWith('@keyframes')).every(s => s.startsWith('@keyframes heritage-')));
const gateway = await readFile(root + 'ui/OceanGateway.tsx', 'utf8');
assert.match(gateway, /<button type="button" className="ocean-gateway" onClick=\{\(\)=>goToEarth\(language\)\}/);
assert.match(gateway, /navigateOcean\(language,oceanArrival,preserveVisit,url=>window.location.assign\(url\)\)/);
assert.ok(!/ocean-handoff|atlas-enter-ocean|setActive/.test(gateway), 'Earth entry cannot be blocked by the departure cover or a delayed scene flight');
const dive = await readFile(root + 'scene/OceanDive.tsx', 'utf8');
assert.ok(!/useFrame|setTimeout|updateProjectionMatrix|lookAt/.test(dive), 'Coordinate capture must never change or continually update the camera');
assert.match(dive, /atlas-ocean-coordinates/);
assert.equal(result.warnings.length, 0);
const earthApp = await readFile('src/App.tsx', 'utf8');
const earthMain = await readFile('src/earth-entry.tsx', 'utf8');
const unified = await readFile('src/styles/unified-ui.css', 'utf8');
assert.match(earthApp, /data-ui-preview="heritage" data-ui-motion=/);
for (const entry of [earthMain,main]) assert.ok(entry.indexOf('unified-ui.css') > entry.indexOf('mobile-ui.css'));
assert.match(unified,/grid-template-columns:44px minmax\(0,1fr\) 44px/);
assert.match(unified,/container:earth-record \/ inline-size/);
assert.match(unified,/@container earth-record \(max-width:620px\)/);
assert.match(unified,/grid-template-rows:auto auto minmax\(0,1fr\)/);
assert.match(unified,/padding:32px 24px 36px/);
assert.match(unified,/min-height:88px/);
assert.match(unified,/min-height:64px;margin:0;padding:16px;font:400 15px\/1.7/);
assert.match(unified,/\.contents-title \{margin:0;font:400 15px\/1.7[^}]*overflow-wrap:anywhere;text-overflow:clip\}/);
assert.match(unified,/\.workspace-panel\.is-floating \.archive-contents \{opacity:1\}/);
assert.match(unified,/\.contents-current>span:last-child \{[^}]*font:400 15px\/1.75/);
const contents = await readFile('src/components/ArchiveContents.tsx','utf8');
assert.match(contents,/aria-expanded=\{expanded\} aria-controls=\{listId\}/);
assert.match(contents,/data-expanded=\{expanded\}/);
assert.match(contents,/function jump\(h:HTMLElement\)\{setExpanded\(false\)/);
assert.match(contents,/style.setProperty\('--contents-menu-height'/);
assert.match(contents,/if\(e.key==='Escape'\)\{e.preventDefault\(\);e.stopPropagation\(\)/);
assert.match(unified,/max-height:min\([^;]*var\(--contents-menu-height,320px\)/);
assert.match(unified,/background:var\(--ui-surface\);border:1px solid var\(--ui-border\)/);
assert.ok(!/transition:all/.test(unified));
assert.equal((await transform(unified,{loader:'css'})).warnings.length,0);
console.log('Shared Earth/Solar default panels, selector scope, mobile offsets, search alignment, motion and CSS compilation passed.');
