import {useEffect,useRef,useState} from 'react';
import {useEarthView,parseCoordinates} from '../../lib/earthEngine';
import {useLanguage} from '../../i18n';
import {useAtlas} from '../../state/store';
import {searchSavedPlaces} from '../../lib/placeSearch';
import {isDenmark} from '../../lib/musicEasterEggs';
const PLACES=[
 {cn:'上海',en:'Shanghai',lon:121.4905,lat:31.2292,range:9000},{cn:'东京',en:'Tokyo',lon:139.752,lat:35.684,range:10000},{cn:'纽约',en:'New York',lon:-74.006,lat:40.7128,range:10000},{cn:'香港',en:'Hong Kong',lon:114.158,lat:22.281,range:12000},{cn:'喜马拉雅山 · 珠穆朗玛峰',en:'Himalayas · Mount Everest',lon:86.925,lat:27.988,range:17000},{cn:'阿尔卑斯山 · 勃朗峰',en:'Alps · Mont Blanc',lon:6.865,lat:45.833,range:13000},{cn:'大峡谷',en:'Grand Canyon',lon:-112.113,lat:36.096,range:16000},{cn:'大堡礁',en:'Great Barrier Reef',lon:146.73,lat:-18.29,range:42000},{cn:'旧金山',en:'San Francisco',lon:-122.419,lat:37.775,range:13000},{cn:'开普敦',en:'Cape Town',lon:18.424,lat:-33.924,range:15000}
];
interface Result {cn:string;en:string;lon:number;lat:number;range:number;}
function distance(value:number){return value>=1000?(value/1000).toLocaleString(undefined,{maximumFractionDigits:1})+' km':Math.round(value)+' m';}
export default function EarthNavigator(){
 const overlay=useAtlas(st=>st.overlay),open=overlay==="search",setOpen=(value:boolean)=>{const st=useAtlas.getState();if(value||st.overlay==="search")st.setOverlay(value?"search":null);};
 const {t,locale}=useLanguage(),s=useEarthView(),[query,setQuery]=useState(''),[remote,setRemote]=useState<Result[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(false),abort=useRef<AbortController|null>(null),last=useRef(0),root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const close=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};document.addEventListener('pointerdown',close);document.addEventListener('keydown',escape);return()=>{abort.current?.abort();document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',escape);};},[]);const results=query.trim()?PLACES.filter(p=>(p.cn+p.en).toLowerCase().includes(query.toLowerCase())):PLACES.slice(0,6);
 const go=(p:Result)=>{useAtlas.getState().setDenmarkMusic(isDenmark(p.cn)||isDenmark(p.en));useAtlas.getState().setPanel(null);s.request({kind:'fly',lon:p.lon,lat:p.lat,range:p.range,pitch:-55});setQuery(locale==='en'?p.en:p.cn);setOpen(false);};
 const search=async()=>{setError(false);useAtlas.getState().setDenmarkMusic(isDenmark(query));const p=parseCoordinates(query);if(p){go({...p,range:14000,cn:query,en:query});return;}if(results.length){go(results[0]);return;}if(query.trim().length<2||performance.now()-last.current<1100)return;last.current=performance.now();abort.current?.abort();const controller=new AbortController();abort.current=controller;setBusy(true);setOpen(true);
 try{ const found=await searchSavedPlaces(query);if(!controller.signal.aborted){setRemote(found);if(!found.length)setError(true);}}catch(e){if(!controller.signal.aborted)setError(true);}finally{if(!controller.signal.aborted)setBusy(false);}
 };
 const labels=useAtlas(st=>st.layers.labels),footer=useRef<HTMLElement>(null);
 useEffect(()=>{const el=footer.current,atlas=el?.closest<HTMLElement>('.atlas');if(!el||!atlas)return;const size=()=>atlas.style.setProperty('--earth-footer-height',`${Math.ceil(el.getBoundingClientRect().height)}px`);const observer=new ResizeObserver(size);observer.observe(el);size();return()=>observer.disconnect();},[]);
 const scale=s.scaleMeters>0?Math.pow(10,Math.floor(Math.log10(s.scaleMeters)))*([1,2,5].reverse().find(n=>n*Math.pow(10,Math.floor(Math.log10(s.scaleMeters)))<=s.scaleMeters)||1):0;
 return <>
  <div className="earth-search" ref={root}><form onSubmit={e=>{e.preventDefault();search();}} role="search"><button type="submit" aria-label={t('搜索地点','Search places')}><svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg></button><input aria-label={t('搜索地点或纬度、经度','Search place or latitude, longitude')} placeholder={t('搜索地球','Search Earth')} value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setRemote([]);setError(false);setOpen(true);}}/><button type="button" aria-label={open?t('关闭搜索结果','Close search results'):t('打开搜索结果','Open search results')} onClick={()=>setOpen(!open)}><span className={open?'search-close':'search-chevron'} aria-hidden="true"/></button></form>
   {open&&<div className="earth-search-results"><p>{busy?t('正在搜索…','Searching…'):query?t('搜索结果','Results'):t('探索地表','Explore the surface')}</p>{[...results,...remote].map((p,i)=><button key={i} onClick={()=>go(p)}><span aria-hidden>⌖</span><span>{locale==='en'?p.en:p.cn}<small>{p.lat.toFixed(3)}°, {p.lon.toFixed(3)}°</small></span><span aria-hidden>↗</span></button>)}{error&&<p role="status">{t('未找到地点，或搜索服务暂不可用。也可输入“纬度, 经度”。','No result or search unavailable. You can enter “latitude, longitude”.')}</p>}<small>{t('本地地名库 · 支持中英文与坐标搜索','Saved gazetteer · Chinese, English and coordinates')}</small></div>}
  </div>
  <div className="earth-navigation" aria-label={t('地球导航','Earth navigation')}>
   <button className="compass" aria-label={t('指向北方','Reset north')} title={t('恢复北向 · N','Reset north · N')} onClick={()=>s.request({kind:'north'})}><span style={{transform:`rotate(${-s.heading}deg)`}}>N<i>▲</i></span></button>
   <button aria-label={t('切换俯视与倾斜视角','Toggle top-down and tilted view')} title={t('倾斜视角 · T','Tilt view · T')} onClick={()=>s.request({kind:'tilt'})}>{s.pitch<-72?'3D':'2D'}</button>
   <button aria-label={t('放大地球','Zoom in')} onClick={()=>s.request({kind:'in'})}>+</button><button aria-label={t('缩小地球','Zoom out')} onClick={()=>s.request({kind:'out'})}>−</button>
   <button aria-label={t('完整地球视角','Frame whole Earth')} title={t('完整地球 · R','Whole Earth · R')} onClick={()=>s.request({kind:'home'})}>◎</button>
  </div>
  <footer ref={footer} className="earth-footer"><div className="earth-readout" aria-live="off">{scale>0&&<span className="earth-distance"><i style={{width:Math.max(20,Math.min(100,scale/s.scaleMeters*100))}}/>{distance(scale)}</span>}<span>{Math.abs(s.lat).toFixed(4)}° {s.lat>=0?'N':'S'} &nbsp; {Math.abs(s.lon).toFixed(4)}° {s.lon>=0?'E':'W'}</span><span>{t('视点高度','Eye altitude')} {distance(s.altitude)}</span><span>{t('高程','Elevation')} {distance(s.ground)}</span></div>
  <div className="earth-attributions"><div id="earth-engine-credit" className="earth-engine-credit"/>
   <a href={s.mapSource==='satellite'?'https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9':s.mapSource==='tianditu'?'https://www.tianditu.gov.cn/':s.mapSource==='geoq'?'https://thematic.geoq.cn/arcgis/rest/services/ChinaOnlineStreetGray/MapServer':'https://science.nasa.gov/earth/earth-observatory/blue-marble-next-generation/base-map/'} target="_blank" rel="noreferrer">{s.mapSource==='satellite'?t('卫星／航空影像 · Esri World Imagery · 非实时','Satellite / aerial imagery · Esri World Imagery · Not live'):s.mapSource==='geoq'?t('国内在线地图 · GeoQ · 远景本地贴图','Domestic online map · GeoQ · Saved globe overview'):s.mapSource==='local'?t('本地底图 · NASA 陆地 2 km/像素 · 海洋 4K · 非实时','Saved basemap · NASA land 2 km/pixel · 4K oceans · Not live'):t('天地图卫星影像','Tianditu satellite imagery')}</a>
   {labels&&<span><a href="https://www.naturalearthdata.com/" target="_blank" rel="noreferrer">Natural Earth</a>{s.externalPlaceDetails&&<> · <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap</a> · <a href="https://carto.com/attributions" target="_blank" rel="noreferrer">© CARTO</a></>}{s.placeNames==='fallback'&&s.altitude<100000&&<span> · {t('细节地名暂不可用，保留基础标注','Local detail unavailable; base names retained')}</span>}</span>}
   <details className="earth-help" open={overlay==="help"} onToggle={e=>{const st=useAtlas.getState();if(e.currentTarget.open&&st.overlay!=="help")st.setOverlay("help");else if(!e.currentTarget.open&&st.overlay==="help")st.setOverlay(null);}}><summary aria-label={t('查看操作说明','View navigation help')}>ⓘ {t('操作','Controls')}</summary><div><span className="desktop-navigation-hint">{t('左键／右键拖动地球 · 以地心为中心 · 中键单击回到全览 · 滚轮缩放 · 双击靠近','Left/right drag: Earth-centred orbit · Middle-click: home · Scroll: zoom · Double-click: approach')} · {t('触控板：滚动缩放，Shift + 拖动旋转','Trackpad: scroll to zoom, Shift-drag to orbit')}</span><span className="touch-navigation-hint">{t('单指绕地核旋转 · 双指拖动与捏合缩放','One finger: geocentre orbit · Two fingers: orbit and pinch')}</span></div></details>
  </div></footer>
  {(s.pending>0||s.imagery==='error'||s.terrain==='error'||s.google==='error')&&<div className="earth-stream-status" role="status">{s.imagery==='error'||s.terrain==='error'?<>{s.imagery==='error'?t('高清影像暂不可用，保留可用底图','Imagery unavailable; retaining basemap'):t('地形加载失败，保留影像','Terrain unavailable; retaining imagery')}<button onClick={()=>s.request({kind:'retry'})}>{t('重试','Retry')}</button></>:s.google==='error'?t('Google 三维数据连接失败，保留卫星影像','Google 3D unavailable; retaining imagery'):t('正在细化地表…','Refining the surface…')}</div>}

 </>;
}
