import {useEffect,useRef,useState} from 'react';
import type * as Cesium from 'cesium';
import {loadEarthEngine,useEarthView,MIN_EYE_HEIGHT,MAX_EYE_HEIGHT,minimumCameraHeight,zoomRange,type Engine,type EarthCommand,type EarthConfig} from '../../lib/earthEngine';
import {useAtlas} from '../../state/store';
import {createSpaceClicks} from '../../lib/spaceClicks';
import {useWeather} from '../../lib/weather';
import {installPrecipitation} from './precipitationRaster';
import {installAdaptiveClouds} from './adaptiveClouds';
import {createGlobalTerrain} from './terrain';
import {configureAtmosphere} from './atmosphere';
import {needsTerrain,detailError,needsScienceRaster,imageryDetailAlpha} from '../../lib/earthDetail';
import {useLanguage} from '../../i18n';
import {isWater,type CurrentField} from '../../lib/currentField';
import {pickCurrent,pickOcean} from '../../lib/pick';
import {addScienceRaster,addScienceRasterAsync,fieldCanvas,addReferenceLayers,addFlow} from './scienceLayers';
import {installEarthDrag,stopEarthDrag,earthDragActive} from './dragController';
import {installPlaceLabels} from './placeLabels';
import {createBasemap,domesticMapMode,createHighDetail,highDetailAlpha} from './basemap';
import {earthRenderBudget,shouldRestoreEarthQuality} from '../../lib/earthPerformance';

function center(C:Engine,v:Cesium.Viewer){const s=v.scene,ray=v.camera.getPickRay(new C.Cartesian2(s.canvas.clientWidth/2,s.canvas.clientHeight/2));return (ray&&s.globe.pick(ray,s))||v.camera.pickEllipsoid(new C.Cartesian2(s.canvas.clientWidth/2,s.canvas.clientHeight/2),s.globe.ellipsoid)||C.Cartesian3.fromRadians(v.camera.positionCartographic.longitude,v.camera.positionCartographic.latitude);}
const intents=new WeakMap<Cesium.Viewer,{point:Cesium.Cartesian3;range:number}>();
function fly(C:Engine,v:Cesium.Viewer,command:EarthCommand){stopEarthDrag(v);if(command.kind!=='in'&&command.kind!=='out')intents.delete(v);v.camera.cancelFlight();const duration=useAtlas.getState().reducedMotion?0:.65;
 if(command.kind==='retry')return;
 if(command.kind==='home'){v.camera.flyTo({destination:C.Cartesian3.fromDegrees(28,-8,19000000),orientation:{heading:0,pitch:-Math.PI/2,roll:0},duration:duration*1.6});return;}
 const intent=(command.kind==='in'||command.kind==='out')?intents.get(v):undefined;
 const point=intent?.point||(command.kind==='fly'?C.Cartesian3.fromDegrees(command.lon!,command.lat!,v.scene.globe.getHeight(C.Cartographic.fromDegrees(command.lon!,command.lat!))||0):center(C,v));
 const distance=intent?.range??C.Cartesian3.distance(v.camera.positionWC,point),range=command.kind==='fly'?command.range||18000:command.kind==='in'?zoomRange(distance,'in'):command.kind==='out'?zoomRange(distance,'out'):distance;
 const pitch=command.kind==='tilt'?(v.camera.pitch<-Math.PI*.4?-Math.PI/4:-Math.PI/2):command.pitch!==undefined?C.Math.toRadians(command.pitch):v.camera.pitch;
 intents.set(v,{point,range});v.camera.flyToBoundingSphere(new C.BoundingSphere(point,1),{complete:()=>intents.delete(v),offset:new C.HeadingPitchRange(command.kind==='north'?0:v.camera.heading,pitch,range),duration});
}
function addStars(C:Engine,v:Cesium.Viewer){const stars=new C.PointPrimitiveCollection();let seed=7919;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<3600;i++){const z=random()*2-1,a=random()*Math.PI*2,r=900000000,s=Math.sqrt(1-z*z);stars.add({position:new C.Cartesian3(r*s*Math.cos(a),r*s*Math.sin(a),r*z),pixelSize:.7+random()**4*2.2,color:new C.Color(.82,.90,1,.25+random()*.55)});}v.scene.primitives.add(stars);return stars;}

export default function GeospatialEarth({field,quality,onScale}:{field:CurrentField;quality:'HIGH'|'MEDIUM'|'LOW';onScale:(scale:string)=>void;onDescend:()=>void}){
 const host=useRef<HTMLDivElement>(null),engine=useRef<Engine|null>(null),viewer=useRef<Cesium.Viewer|null>(null),fieldRef=useRef(field),[ready,setReady]=useState(false),[attempt,setAttempt]=useState(0),[error,setError]=useState(false),[cloudError,setCloudError]=useState(false),[cloudAttempt,setCloudAttempt]=useState(0);
 fieldRef.current=field;const layers=useAtlas(s=>s.layers),locale=useAtlas(s=>s.locale),grid=useWeather(s=>s.grid),needsWeather=useAtlas(s=>s.layers.wind||s.layers.rain||s.layers.cloudcover||s.panel==='weather'),{t}=useLanguage();
 useEffect(()=>{let alive=true;const cleanup:(()=>void)[]=[];useEarthView.setState({ready:false,detail:'off',imagery:'loading',terrain:'loading'});setError(false);
 loadEarthEngine().then(C=>{if(!alive||!host.current)return;engine.current=C;
 const v=new C.Viewer(host.current,{creditContainer:document.getElementById('earth-engine-credit')||undefined,baseLayer:false,terrainProvider:new C.EllipsoidTerrainProvider(),animation:false,timeline:false,baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,fullscreenButton:false,infoBox:false,selectionIndicator:false,useBrowserRecommendedResolution:false,shouldAnimate:false,skyBox:false,requestRenderMode:true,maximumRenderTimeChange:Infinity,contextOptions:{webgl:{alpha:false,antialias:false,powerPreference:'high-performance'}}});viewer.current=v;
 cleanup.push(v.scene.renderError.addEventListener(()=>{if(alive){setError(true);setReady(false);}}));
 v.scene.backgroundColor=C.Color.fromCssColorString('#020407');v.scene.globe.baseColor=C.Color.fromCssColorString('#203e54');v.scene.globe.enableLighting=false;v.scene.globe.showGroundAtmosphere=true;v.scene.globe.depthTestAgainstTerrain=true;v.scene.highDynamicRange=true;v.scene.postProcessStages.fxaa.enabled=true;v.scene.globe.tileCacheSize=120;v.scene.globe.preloadSiblings=false;v.scene.globe.maximumScreenSpaceError=1.8;v.resolutionScale=1;v.scene.fog.density=.00012;
 const controller=v.scene.screenSpaceCameraController;controller.minimumZoomDistance=MIN_EYE_HEIGHT;controller.maximumZoomDistance=MAX_EYE_HEIGHT;controller.enableCollisionDetection=true;controller.maximumTiltAngle=Math.PI/2-.06;controller.inertiaSpin=.88;controller.inertiaZoom=.82;controller.inertiaTranslate=.88;controller.rotateEventTypes=[C.CameraEventType.LEFT_DRAG];controller.translateEventTypes=[C.CameraEventType.LEFT_DRAG];controller.zoomEventTypes=[C.CameraEventType.WHEEL,C.CameraEventType.PINCH];controller.tiltEventTypes=[C.CameraEventType.RIGHT_DRAG,C.CameraEventType.MIDDLE_DRAG,C.CameraEventType.PINCH,{eventType:C.CameraEventType.LEFT_DRAG,modifier:C.KeyboardEventModifier.CTRL},{eventType:C.CameraEventType.LEFT_DRAG,modifier:C.KeyboardEventModifier.SHIFT}];
 v.screenSpaceEventHandler.removeInputAction(C.ScreenSpaceEventType.LEFT_DOUBLE_CLICK);
 v.camera.setView({destination:C.Cartesian3.fromDegrees(28,-8,19000000),orientation:{heading:0,pitch:-Math.PI/2,roll:0}});
 const canvas=v.scene.canvas;const cancelIntent=()=>{intents.delete(v);v.camera.cancelFlight();};const preventContext=(e:MouseEvent)=>e.preventDefault();canvas.addEventListener('contextmenu',preventContext);cleanup.push(()=>canvas.removeEventListener('contextmenu',preventContext));canvas.addEventListener('pointerdown',cancelIntent);canvas.addEventListener('wheel',cancelIntent,{passive:true});cleanup.push(()=>{canvas.removeEventListener('pointerdown',cancelIntent);canvas.removeEventListener('wheel',cancelIntent);});canvas.tabIndex=0;canvas.setAttribute('aria-label',useAtlas.getState().locale==='en'?'Interactive geographic globe':'可拖动、缩放及倾斜的地理地球');
 cleanup.push(installEarthDrag(C,v,()=>center(C,v)));cleanup.push(installPlaceLabels(C,v,()=>fieldRef.current));
 // A saved global photograph remains visible while streaming tiles load or fail.
 const fallback=new C.SingleTileImageryProvider({url:'/earth/solar-earth_daymap-4k.jpg',tileWidth:4096,tileHeight:2048,rectangle:C.Rectangle.MAX_VALUE,credit:new C.Credit('Solar System Scope · CC BY 4.0')});v.imageryLayers.addImageryProvider(fallback);
 let streamedImagery:Cesium.ImageryLayer|null=null,highImagery:Cesium.ImageryLayer|null=null;
 const ensureDetail=()=>{const source=domesticMapMode(mapConfig);if(highImagery||source!=='geoq'&&source!=='satellite')return;const provider=createHighDetail(C,source);provider.errorEvent.addEventListener(()=>{if(alive)useEarthView.setState({detail:'error'});});highImagery=v.imageryLayers.addImageryProvider(provider,2);highImagery.brightness=1;highImagery.show=false;useEarthView.setState({detail:'loading'});};

 let mapConfig:EarthConfig={mapSource:'satellite'};
 const connectImagery=()=>{useEarthView.setState({imagery:'loading'});try{const p=createBasemap(C,mapConfig);p.errorEvent.addEventListener(()=>{if(alive)useEarthView.setState({imagery:'error'});});if(streamedImagery)v.imageryLayers.remove(streamedImagery,true);const layer=v.imageryLayers.addImageryProvider(p,1);streamedImagery=layer;layer.alpha=imageryDetailAlpha(v.camera.positionCartographic.height);layer.show=layer.alpha>0;useEarthView.setState({imagery:'ready',mapSource:domesticMapMode(mapConfig)});v.scene.requestRender();}catch{if(alive)useEarthView.setState({imagery:'error'});}};
 let disposeTerrain:(()=>void)|undefined;cleanup.push(()=>disposeTerrain?.());let terrain:Cesium.CustomHeightmapTerrainProvider|null=null;const flatTerrain=new C.EllipsoidTerrainProvider();
 const connectTerrain=()=>{useEarthView.setState({terrain:'loading'});try{disposeTerrain?.();const globalTerrain=createGlobalTerrain(C);terrain=globalTerrain.provider;disposeTerrain=globalTerrain.dispose;terrain.errorEvent.addEventListener(()=>{if(alive)useEarthView.setState({terrain:'error'});});useEarthView.setState({terrain:'ready'});}catch{useEarthView.setState({terrain:'error'});}};connectImagery();useEarthView.setState({terrain:'ready'});
 fetch('/earth-config.json').then(r=>r.json()).then((config:EarthConfig)=>{
  if(!alive)return;mapConfig=config;useEarthView.setState({externalPlaceDetails:false,externalTerrain:config.externalTerrain===true,google:'off'});
  if(highImagery){v.imageryLayers.remove(highImagery,true);highImagery=null;useEarthView.setState({detail:'off'});}connectImagery();
  if(config.externalTerrain===true)connectTerrain();
 }).catch(()=>{});
 const stars=addStars(C,v);const atmosphere=configureAtmosphere(C,v);cleanup.push(atmosphere.dispose);
 let moving=false,terrainActive=false,lastMotion=performance.now(),settleTimer:ReturnType<typeof setTimeout>|undefined;
 const resolution=(active=false)=>{const q=useAtlas.getState().quality,w=canvas.clientWidth,h=canvas.clientHeight,budget=earthRenderBudget(w,h,window.devicePixelRatio||1,q,active);v.resolutionScale=budget.scale;v.scene.globe.maximumScreenSpaceError=budget.screenError;v.scene.highDynamicRange=false;v.scene.globe.loadingDescendantLimit=12;v.targetFrameRate=q==='LOW'||Math.min(w,h)<500?30:60;v.scene.globe.tileCacheSize=Math.min(w,h)<500?48:120;if(v.scene.skyAtmosphere)v.scene.skyAtmosphere.perFragmentAtmosphere=!active&&q==='HIGH';(v.container as HTMLElement).dataset.earthMoving=String(active);(v.container as HTMLElement).dataset.earthResolution=budget.scale.toFixed(3);v.container.closest('.atlas')?.setAttribute('data-camera-moving',String(active));};resolution();const sizeObserver=new ResizeObserver(()=>{resolution(moving);v.scene.requestRender();});sizeObserver.observe(canvas);cleanup.push(()=>sizeObserver.disconnect());cleanup.push(useAtlas.subscribe((s,p)=>{if(s.quality!==p.quality){resolution(moving);v.scene.requestRender();}}));
 const settle=()=>{if(!alive||earthDragActive(v))return;moving=false;resolution();telemetryDirty=true;v.scene.requestRender();};
 // Resolution/frustum updates can themselves emit moveStart. Actual world-pose
 // changes below are the source of truth, avoiding a quality-toggle feedback loop.
 cleanup.push(v.camera.moveEnd.addEventListener(()=>{settleTimer=setTimeout(settle,220);}));
 const motionWatchdog=setInterval(()=>{const now=performance.now(),active=earthDragActive(v);(v.container as HTMLElement).dataset.earthIdleMs=String(Math.round(now-lastMotion));(v.container as HTMLElement).dataset.earthGestureActive=String(active);if(moving&&shouldRestoreEarthQuality(now,lastMotion,active))settle();},200);cleanup.push(()=>clearInterval(motionWatchdog));
 cleanup.push(()=>clearTimeout(settleTimer));
 let lastTelemetry=0,lastScale='',telemetryDirty=true;const lastPosition=new C.Cartesian3(),lastDirection=new C.Cartesian3();
 cleanup.push(v.scene.globe.tileLoadProgressEvent.addEventListener((pending:number)=>{if(!alive)return;const state=useEarthView.getState(),detail=pending===0&&highImagery?.show&&state.detail!=='error'?'ready':state.detail;if(pending!==state.pending||detail!==state.detail)useEarthView.setState({pending,detail});if(pending===0)telemetryDirty=true;}));
 cleanup.push(v.scene.preUpdate.addEventListener(()=>{const st=useAtlas.getState(),h=v.camera.positionCartographic.height;const detailAlpha=highDetailAlpha(h,st.quality);if(detailAlpha>0&&!moving)ensureDetail();if(highImagery){highImagery.alpha=detailAlpha;highImagery.show=detailAlpha>0;}if(streamedImagery){streamedImagery.alpha=imageryDetailAlpha(h);streamedImagery.show=streamedImagery.alpha>0;}v.scene.requestRenderMode=true;v.scene.postProcessStages.fxaa.enabled=moving||st.quality==='LOW'||['wind','currents','rain'].some(k=>st.layers[k]);if(terrain){terrainActive=needsTerrain(h,terrainActive,st.layers.landrelief,moving);const target=terrainActive?terrain:flatTerrain;if(v.terrainProvider!==target)v.terrainProvider=target;}stars.show=st.layers.stars;atmosphere.halo.enabled=st.layers.atmosphere;if(v.scene.skyAtmosphere)v.scene.skyAtmosphere.show=st.layers.atmosphere;v.scene.globe.showGroundAtmosphere=st.layers.atmosphere;
 const changed=!C.Cartesian3.equalsEpsilon(lastPosition,v.camera.positionWC,0,.05)||!C.Cartesian3.equalsEpsilon(lastDirection,v.camera.directionWC,0,1e-9);if(changed){lastMotion=performance.now();if(!moving){moving=true;resolution(true);}C.Cartesian3.clone(v.camera.positionWC,lastPosition);C.Cartesian3.clone(v.camera.directionWC,lastDirection);telemetryDirty=true;}if(!telemetryDirty)return;
 const cameraLocation=v.camera.positionCartographic;if(h<100000){const ground=v.scene.globe.getHeight(cameraLocation)||0;if(cameraLocation.height<minimumCameraHeight(ground)){cameraLocation.height=minimumCameraHeight(ground);v.camera.position=C.Cartesian3.fromRadians(cameraLocation.longitude,cameraLocation.latitude,cameraLocation.height);}}
 const now=performance.now();if(now-lastTelemetry<(moving?300:160))return;lastTelemetry=now;telemetryDirty=false;const point=center(C,v),location=C.Cartographic.fromCartesian(point),left=v.camera.getPickRay(new C.Cartesian2(v.scene.canvas.clientWidth/2-50,v.scene.canvas.clientHeight/2)),right=v.camera.getPickRay(new C.Cartesian2(v.scene.canvas.clientWidth/2+50,v.scene.canvas.clientHeight/2)),a=left&&v.scene.globe.pick(left,v.scene),b=right&&v.scene.globe.pick(right,v.scene);
 useEarthView.setState({lon:C.Math.toDegrees(location.longitude),lat:C.Math.toDegrees(location.latitude),altitude:v.camera.positionCartographic.height,ground:Math.max(0,v.scene.globe.getHeight(location)||0),heading:C.Math.toDegrees(v.camera.heading),pitch:C.Math.toDegrees(v.camera.pitch),scaleMeters:a&&b?C.Cartesian3.distance(a,b):0});const scale=h>10000000?'GLOBAL':h>2000000?'OCEAN':h>300000?'REGION':h>12000?'LOCAL':'SURFACE';if(scale!==lastScale){lastScale=scale;onScale(scale);}
 }));
 const handler=new C.ScreenSpaceEventHandler(canvas),spaceClicks=createSpaceClicks();const hit=(position:Cesium.Cartesian2)=>{const ray=v.camera.getPickRay(position);return (ray&&v.scene.globe.pick(ray,v.scene))||v.camera.pickEllipsoid(position,v.scene.globe.ellipsoid);};let clickTimer:ReturnType<typeof setTimeout>|undefined;const inspect=(e:{position:Cesium.Cartesian2})=>{const picked=v.scene.pick(e.position);const id=picked?.id?.id as string|undefined;if(id?.startsWith('current:')){useAtlas.getState().select({kind:'current',id:id.split(':')[1]});return;}if(id?.startsWith('dive:')){useAtlas.getState().select({kind:'dive',id:id.slice(5)});return;}const ray=v.camera.getPickRay(e.position),point=(ray&&v.scene.globe.pick(ray,v.scene))||v.camera.pickEllipsoid(e.position,v.scene.globe.ellipsoid);if(!point){useAtlas.getState().closeUi();return;}const pos=C.Cartographic.fromCartesian(point),lon=C.Math.toDegrees(pos.longitude),lat=C.Math.toDegrees(pos.latitude),st=useAtlas.getState();if(st.panel==='weather'){useWeather.getState().inspect(lon,lat);return;}const f=fieldRef.current,c=st.layers.currents&&isWater(f,lon,lat)?pickCurrent(lon,lat):null,o=isWater(f,lon,lat)?pickOcean(lon,lat):null;if(c)st.select({kind:'current',id:c.id});else if(o)st.select({kind:'ocean',id:o.id});else st.setPanel('earth');};handler.setInputAction((e:{position:Cesium.Cartesian2})=>{clearTimeout(clickTimer);if(!hit(e.position)){const action=spaceClicks.click(performance.now(),e.position.x,e.position.y);useAtlas.getState().closeUi();if(action==='open')useAtlas.getState().setPanel('sky');return;}spaceClicks.reset();clickTimer=setTimeout(()=>inspect(e),280);},C.ScreenSpaceEventType.LEFT_CLICK);
 handler.setInputAction((e:{position:Cesium.Cartesian2})=>{clearTimeout(clickTimer);const point=hit(e.position);if(!point){spaceClicks.reset();useAtlas.getState().setPanel('sky');return;}spaceClicks.reset();useAtlas.getState().closeUi();if(point){const p=C.Cartographic.fromCartesian(point);fly(C,v,{kind:'fly',lon:C.Math.toDegrees(p.longitude),lat:C.Math.toDegrees(p.latitude),range:Math.max(60,C.Cartesian3.distance(v.camera.positionWC,point)*.45),pitch:C.Math.toDegrees(v.camera.pitch),key:performance.now()});}},C.ScreenSpaceEventType.LEFT_DOUBLE_CLICK);
 const key=(e:KeyboardEvent)=>{if(e.target!==canvas)return;const command=e.key==='+'||e.key==='='?'in':e.key==='-'?'out':e.key==='n'||e.key==='N'?'north':e.key==='r'||e.key==='R'?'home':e.key==='t'||e.key==='T'?'tilt':null;if(command){e.preventDefault();fly(C,v,{kind:command,key:performance.now()});}else if(e.key.startsWith('Arrow')){e.preventDefault();stopEarthDrag(v);intents.delete(v);v.camera.cancelFlight();const amount=Math.min(.12,Math.max(.000002,v.camera.positionCartographic.height/6378137*.12));if(e.shiftKey){if(e.key==='ArrowLeft')v.camera.rotateLeft(.04);if(e.key==='ArrowRight')v.camera.rotateRight(.04);if(e.key==='ArrowUp')v.camera.rotateUp(.04);if(e.key==='ArrowDown')v.camera.rotateDown(.04);}else{if(e.key==='ArrowLeft')v.camera.rotateLeft(amount);if(e.key==='ArrowRight')v.camera.rotateRight(amount);if(e.key==='ArrowUp')v.camera.rotateUp(amount);if(e.key==='ArrowDown')v.camera.rotateDown(amount);}}};canvas.addEventListener('keydown',key);cleanup.push(()=>{clearTimeout(clickTimer);canvas.removeEventListener('keydown',key);handler.destroy();});
 cleanup.push(useEarthView.subscribe((s,previous)=>{if(s.command?.key===previous.command?.key||!s.command)return;if(s.command.kind==='retry'){if(s.detail==='error'&&highImagery){v.imageryLayers.remove(highImagery,true);highImagery=null;useEarthView.setState({detail:'off'});}if(s.imagery==='error')connectImagery();if(s.terrain==='error'&&mapConfig.externalTerrain)connectTerrain();}else fly(C,v,s.command);}));
 cleanup.push(useAtlas.subscribe((s,p)=>{if(s.layers!==p.layers||s.quality!==p.quality||s.reducedMotion!==p.reducedMotion)v.scene.requestRender();if(s.cameraAction?.key!==p.cameraAction?.key&&s.cameraAction)fly(C,v,{kind:s.cameraAction.kind,key:s.cameraAction.key});if(s.focus?.key!==p.focus?.key&&s.focus){const height=Math.max(400000,v.camera.positionCartographic.height);fly(C,v,{kind:'fly',lon:s.focus.lon,lat:s.focus.lat,range:height,pitch:-90,key:s.focus.key});}}));
 const query=new URLSearchParams(location.search),lon=Number(query.get('lon')),lat=Number(query.get('lat')),range=Number(query.get('range')),pitch=Number(query.get('pitch'));if(query.has('lon')&&query.has('lat')&&Number.isFinite(lon)&&Number.isFinite(lat)&&Math.abs(lon)<=180&&Math.abs(lat)<=90&&query.get('from')!=='solar')fly(C,v,{kind:'fly',lon,lat,range:query.has('range')&&Number.isFinite(range)?Math.max(60,Math.min(MAX_EYE_HEIGHT,range)):19000000,pitch:query.has('pitch')&&Number.isFinite(pitch)?Math.max(-90,Math.min(-15,pitch)):-90,key:performance.now()});
 const initial=useAtlas.getState().focus;if(initial)fly(C,v,{kind:'fly',lon:initial.lon,lat:initial.lat,range:19000000,pitch:-90,key:initial.key});
 useEarthView.setState({ready:true});setReady(true);
 }).catch(()=>{if(alive)setError(true);});return()=>{alive=false;cleanup.forEach(fn=>fn());if(viewer.current&&!viewer.current.isDestroyed())viewer.current.destroy();viewer.current=null;useEarthView.setState({ready:false});};
 },[attempt]);
 useEffect(()=>{const C=engine.current,v=viewer.current;if(!ready||!C||!v)return;setCloudError(false);return installAdaptiveClouds(C,v,quality,setCloudError);},[ready,quality,cloudAttempt]);
 useEffect(()=>{if(!ready||!needsWeather)return;const load=()=>{if(!document.hidden)useWeather.getState().load();};load();const id=setInterval(load,60000);const visible=()=>{if(!document.hidden&&Date.now()-useWeather.getState().lastChecked>60000)load();};document.addEventListener('visibilitychange',visible);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',visible);};},[ready,needsWeather]);
 useEffect(()=>{const v=viewer.current;if(!ready||!v||v.isDestroyed())return;v.scene.globe.maximumScreenSpaceError=earthRenderBudget(v.scene.canvas.clientWidth,v.scene.canvas.clientHeight,window.devicePixelRatio,quality,(v.container as HTMLElement).dataset.earthMoving==='true').screenError;},[quality,ready]);
 useEffect(()=>{const v=viewer.current;if(ready&&v)v.scene.canvas.setAttribute('aria-label',locale==='en'?'Interactive geographic globe':'可拖动、缩放及倾斜的地理地球');},[locale,ready]);
 useEffect(()=>{const C=engine.current,v=viewer.current;if(!ready||!C||!v)return;return addFlow(C,v,field,grid);},[ready,field,layers.wind,layers.currents,grid?.values,quality]);
 useEffect(()=>{const C=engine.current,v=viewer.current;if(!ready||!C||!v)return;return addReferenceLayers(C,v,layers,locale,field);},[ready,field,locale,layers.currents,layers.graticule,layers.boundaries,layers.windbelts,layers.divesites]);
 useEffect(()=>{const C=engine.current,v=viewer.current;if(!ready||!C||!v||!layers.rain||!grid)return;return installPrecipitation(C,v,grid,quality);},[ready,grid?.values,quality,layers.rain]);
 useEffect(()=>{const C=engine.current,v=viewer.current;if(!ready||!C||!v||!needsScienceRaster(layers)||layers.rain&&layers.land&&layers.ocean)return;const abort=new AbortController();let remove=()=>{};
 fieldCanvas(field,grid,{...layers,rain:false},abort.signal).then(canvas=>addScienceRasterAsync(C,v,canvas,abort.signal)).then(cleanup=>{if(abort.signal.aborted)cleanup();else remove=cleanup;}).catch(()=>{});
 return()=>{abort.abort();remove();};},[ready,field,grid?.values,grid?.clouds,quality,layers.wind,layers.rain,layers.cloudcover,layers.field,layers.warmcold,layers.land,layers.ocean]);
 useEffect(()=>{const C=engine.current,v=viewer.current;if(!ready||!C||!v||!layers.relief)return;let disposed=false,remove=()=>{};const depth=new Image();depth.src='/earth/earth-depth.png';depth.onload=()=>{if(disposed||v.isDestroyed())return;const canvas=document.createElement('canvas');canvas.width=depth.width;canvas.height=depth.height;const ctx=canvas.getContext('2d')!;ctx.drawImage(depth,0,0);const data=ctx.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<data.data.length;i+=4){const d=data.data[i]/255;data.data[i]=8+(1-d)*15;data.data[i+1]=30+(1-d)*80;data.data[i+2]=55+(1-d)*90;const pixel=i/4,x=pixel%canvas.width,y=Math.floor(pixel/canvas.width);data.data[i+3]=isWater(field,-180+(x+.5)*360/canvas.width,90-(y+.5)*180/canvas.height)?170:0;}ctx.putImageData(data,0,0);remove=addScienceRaster(C,v,canvas);};return()=>{disposed=true;remove();};},[ready,field,layers.relief]);
 return <div className="geospatial-earth" ref={host} data-engine="cesium" data-ready={ready}>{cloudError&&layers.clouds&&<div className="earth-cloud-error" role="alert">{t("摄影云层加载失败","Photographic clouds unavailable")} <button onClick={()=>setCloudAttempt(n=>n+1)}>{t("重试","Retry")}</button></div>}{!ready&&!error&&<div className="earth-loading" role="status">{t('正在展开地球…','Opening Earth…')}</div>}{error&&<div className="earth-loading" role="alert"><p>{t('地球引擎暂不可用','Earth is temporarily unavailable')}</p><button onClick={()=>setAttempt(v=>v+1)}>{t('重试','Retry')}</button><button onClick={()=>useAtlas.getState().setPanel('library')}>{t('打开资料库','Open library')}</button></div>}</div>;
}
