import {readFile,mkdir,writeFile,rename} from 'node:fs/promises';
import {join} from 'node:path';
import {decodeGFS} from './netcdf.mjs';
export const GFS_ENDPOINT='https://tds.scigw.unidata.ucar.edu/thredds/ncss/grid/grib/NCEP/GFS/Global_0p25deg/Best';
export function gfsURL(){const params=new URLSearchParams();for(const v of ['u-component_of_wind_height_above_ground','v-component_of_wind_height_above_ground','Precipitation_rate_surface','Total_cloud_cover_entire_atmosphere'])params.append('var',v);for(const [k,v] of Object.entries({north:90,south:-90,west:0,east:360,horizStride:1,time:'present',vertCoord:10,accept:'netcdf3'}))params.set(k,String(v));return GFS_ENDPOINT+'?'+params;}
export async function saveWeather(root,data){const dir=join(root,'weather');await mkdir(dir,{recursive:true});for(const [name,body] of [['gfs-surface.bin',Buffer.from(data.values.buffer)],['gfs-clouds.bin',Buffer.from(data.clouds.buffer)],['gfs-surface.json',JSON.stringify(data.meta,null,2)+'\n']]){await writeFile(join(dir,name+'.tmp'),body);await rename(join(dir,name+'.tmp'),join(dir,name));}}
export function environmentFeed(root){
 let current=null,pending=null,next=0,failure=false,lastChecked=0;const history=new Map();
 const remember=d=>{current=d;const version=d.meta.downloadedAt;history.set(version,d);if(history.size>3)history.delete(history.keys().next().value);};
 const packaged=async()=>{if(current)return;try{const meta=JSON.parse(await readFile(join(root,'weather/gfs-surface.json'),'utf8')),raw=await readFile(join(root,meta.binary.slice(1))),cloud=meta.cloudBinary?await readFile(join(root,meta.cloudBinary.slice(1))):null;remember({meta,values:raw,clouds:cloud});next=Math.max(next,Date.parse(meta.downloadedAt)+3600000);}catch{}};
 const refresh=()=>{if(pending||Date.now()<next)return;lastChecked=Date.now();next=lastChecked+3600000;failure=false;pending=(async()=>{try{const url=gfsURL(),r=await fetch(url,{signal:AbortSignal.timeout(1800000)});if(!r.ok)throw Error('GFS HTTP '+r.status);const data=decodeGFS(await r.arrayBuffer(),url);if(current&&Date.parse(data.meta.validTime)<Date.parse(current.meta.validTime))throw Error('Older forecast rejected');await saveWeather(root,data);remember({...data,values:Buffer.from(data.values.buffer),clouds:Buffer.from(data.clouds.buffer)});console.log('GFS refreshed:',data.meta.validTime,data.meta.width+'×'+data.meta.height);}catch(e){failure=true;next=Date.now()+600000;console.warn('GFS refresh failed; retaining snapshot:',e.message);}finally{pending=null;}})();};
 return async(req,res)=>{const url=new URL(req.url,'http://localhost');if(!url.pathname.startsWith('/api/environment/'))return false;await packaged();refresh();if(!current){res.writeHead(503,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify({error:'No forecast available',updating:Boolean(pending)}));return true;}const requested=url.searchParams.get('version'),selected=requested?history.get(requested):current;
 if(url.pathname==='/api/environment/weather.json'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify({...current.meta,binary:'/api/environment/weather.bin?version='+encodeURIComponent(current.meta.downloadedAt),cloudBinary:current.clouds?'/api/environment/clouds.bin?version='+encodeURIComponent(current.meta.downloadedAt):undefined,feed:'online',updating:Boolean(pending),refreshFailed:failure,lastCheckedAt:lastChecked?new Date(lastChecked).toISOString():current.meta.downloadedAt}));return true;}
 if(url.pathname==='/api/environment/weather.bin'||url.pathname==='/api/environment/clouds.bin'){const body=url.pathname.includes('clouds')?selected?.clouds:selected?.values;if(!body){res.writeHead(404);res.end();return true;}res.writeHead(200,{'content-type':'application/octet-stream','cache-control':'no-cache'});res.end(body);return true;}
 res.writeHead(404);res.end();return true;};
}
