import {readFile,writeFile,mkdir,stat,rename,readdir,unlink} from 'node:fs/promises';
import {join} from 'node:path';
export const DETAIL_ORIGIN='https://thematic.geoq.cn/arcgis/rest/services/ChinaOnlineStreetGray/MapServer/tile';
export const SATELLITE_ORIGIN='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile';
export function detailTilePath(path){const m=/^\/api\/imagery\/(geoq-gray|world-imagery)\/(\d+)\/(\d+)\/(\d+)\.(png|jpg)$/.exec(path);if(!m||m[5]!== (m[1]==='geoq-gray'?'png':'jpg'))return null;const [z,y,x]=m.slice(2,5).map(Number);return z<=(m[1]==='geoq-gray'?19:18)&&x<2**z&&y<2**z?{z,y,x}:null;}
/** Fixed public imagery source, bounded concurrency and on-demand display cache.
 * No arbitrary URLs, keys or user data are forwarded to the upstream service. */
export function imageryFeed(root,{fetchTile=fetch,timeout=12000,cacheDir=join(root,'..','.cache','imagery')}={}){
 const pending=new Map(),negative=new Map();let active=0;const queue=[];let trimmed=false,writes=0;
 const trim=async()=>{if(trimmed)return;trimmed=true;await mkdir(cacheDir,{recursive:true});const files=(await readdir(cacheDir)).filter(n=>/\.(png|jpg)$/.test(n));const entries=await Promise.all(files.map(async name=>({name,s:await stat(join(cacheDir,name))})));entries.sort((a,b)=>b.s.mtimeMs-a.s.mtimeMs);let bytes=0;for(const e of entries){bytes+=e.s.size;if(bytes>100*1024*1024||Date.now()-e.s.mtimeMs>30*86400000)await unlink(join(cacheDir,e.name)).catch(()=>{});}};
 const enter=async()=>{if(active>=4)await new Promise(r=>queue.push(r));else active++;};
 const leave=()=>{const next=queue.shift();if(next)next();else active--;};
 const load=async(t,satellite)=>{const key=`${satellite?'satellite':'geoq'}-${t.z}-${t.y}-${t.x}`,file=join(cacheDir,key+(satellite?'.jpg':'.png'));const stored=await stat(file).catch(()=>null);if(stored&&Date.now()-stored.mtimeMs<86400000)return readFile(file);if(negative.get(key)>Date.now())throw Error('Source temporarily unavailable');if(pending.has(key))return pending.get(key);if(pending.size>=64)throw Error('Tile queue full');const work=(async()=>{await enter();try{const r=await fetchTile(`${satellite?SATELLITE_ORIGIN:DETAIL_ORIGIN}/${t.z}/${t.y}/${t.x}`,{signal:AbortSignal.timeout(timeout)});if(!r.ok)throw Error('Imagery HTTP '+r.status);const body=Buffer.from(await r.arrayBuffer());const valid=satellite?body[0]===255&&body[1]===216&&body[2]===255:body.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));if(body.length>2*1024*1024||!valid)throw Error('Invalid imagery');await mkdir(cacheDir,{recursive:true});await writeFile(file+'.tmp',body);await rename(file+'.tmp',file);if(++writes%128===0){trimmed=false;await trim();}return body;}catch(e){negative.set(key,Date.now()+30000);if(negative.size>256)negative.delete(negative.keys().next().value);throw e;}finally{leave();pending.delete(key);}})();pending.set(key,work);return work;};
 return async(req,res)=>{const path=new URL(req.url,'http://localhost').pathname;if(!path.startsWith('/api/imagery/'))return false;if(!['GET','HEAD'].includes(req.method||'GET')){res.writeHead(405);res.end('Method not allowed');return true;}const tile=detailTilePath(path),satellite=path.includes('/world-imagery/');if(!tile){res.writeHead(400);res.end('Invalid tile');return true;}try{await trim();const body=await load(tile,satellite);res.writeHead(200,{'content-type':satellite?'image/jpeg':'image/png','cache-control':'public, max-age=86400','x-imagery-source':satellite?'Esri World Imagery; satellite and aerial photography':'GeoQ ChinaOnlineStreetGray; domestic street basemap'});res.end(req.method==='HEAD'?undefined:body);}catch{res.writeHead(503,{'cache-control':'no-store','retry-after':'30'});res.end('Detail imagery unavailable; retain local basemap');}return true;};
}
