import {useEffect,useMemo} from 'react';
import * as THREE from 'three';
import {useFrame,type ThreeEvent} from '@react-three/fiber';
import {useTexture} from '@react-three/drei';
import {VERT,FRAG} from '../../shared/planetShaders';
import {SUN_DIRECTION} from './lighting';
import {useAtlas} from '../../state/store';
export interface EarthProps {radius:number;currentMap:THREE.Texture;warmMap:THREE.Texture;showField:boolean;geoMode:boolean;showClouds:boolean;showSeaRelief:boolean;showAirglow:boolean;reducedMotion:boolean;onPointerMove:(e:ThreeEvent<PointerEvent>)=>void;onPointerOut:()=>void;onClick:(e:ThreeEvent<MouseEvent>)=>void;}
const fragment=FRAG.replace('uniform vec3 uSunPosition;',`uniform vec3 uSunPosition;uniform sampler2D uWaterMask,uDepth,uCurrent,uWarm;uniform float uMaskMode,uFieldOn,uWarmOn,uReliefOn;`).replace('vec3 N = normalize(vNormalW);',`float water=step(.43,texture2D(uWaterMask,vUv).r);if((uMaskMode<.5&&water>.5)||(uMaskMode>.5&&water<.5))discard;vec3 N = normalize(vNormalW);`).replace('gl_FragColor = vec4(col * uDim, 1.0);',`float speed=texture2D(uCurrent,vUv).b;float warm=texture2D(uWarm,vUv).r;vec3 field=mix(vec3(.025,.20,.35),vec3(.76,.37,.08),speed);col=mix(col,field,water*uFieldOn*.5);col=mix(col,mix(vec3(.025,.3,.55),vec3(.8,.23,.04),warm),water*uWarmOn*.38);float d=texture2D(uDepth,vUv).r;col=mix(col,mix(vec3(.045,.17,.22),vec3(.006,.025,.08),d),water*uReliefOn*.7);gl_FragColor=vec4(col*uDim,1.);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>`);
const cloudVertex=`varying vec2 vUv;varying vec3 n,p;void main(){vUv=uv;vec4 w=modelMatrix*vec4(position,1.);p=w.xyz;n=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*viewMatrix*w;}`;
// The solar atlas optical cloud shell, with the same coverage response and lighting.
const cloudFragment=`uniform sampler2D uMap;uniform float uTime,uOpacity;uniform vec3 sun;varying vec2 vUv;varying vec3 p,n;void main(){vec2 uv=vec2(fract(vUv.x+uTime*.00012),vUv.y);float c=texture2D(uMap,uv).r;float coverage=1.-exp(-pow(max(c,0.),1.5)*1.9);if(coverage<.004)discard;vec3 N=normalize(n),L=normalize(sun-p),V=normalize(cameraPosition-p);float day=pow(max(dot(N,L),0.),.58),forward=pow(max(dot(-L,V),0.),5.);vec3 col=vec3(.87,.92,1.)*(.0015+day*.94)+vec3(.12,.18,.25)*forward*day*.10;gl_FragColor=vec4(col,coverage*uOpacity);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>}`;
const TEXTURES=['/earth/solar-earth_daymap-4k.jpg','/earth/solar-earth_clouds-4k.jpg','/earth/solar-earth_nightmap-2k.jpg','/earth/earth-mask.png','/earth/earth-depth.png'];
export default function Earth(p:EarthProps){const [day,cloud,night,mask,depth]=useTexture(TEXTURES),layers=useAtlas(s=>s.layers);
 useEffect(()=>{day.colorSpace=night.colorSpace=THREE.SRGBColorSpace;for(const tex of [day,cloud,night,mask,depth]){tex.wrapS=THREE.RepeatWrapping;tex.anisotropy=8;tex.needsUpdate=true;}},[day,cloud,night,mask,depth]);
 const materials=useMemo(()=>[0,1].map(mode=>new THREE.ShaderMaterial({vertexShader:VERT,fragmentShader:fragment,uniforms:{uSunPosition:{value:SUN_DIRECTION.clone().multiplyScalar(100)},uMap:{value:day},uHasMap:{value:1},uNight:{value:night},uClouds:{value:cloud},uHasClouds:{value:1},uTime:{value:0},uColorA:{value:new THREE.Color('#547fbd')},uColorB:{value:new THREE.Color('#183963')},uColorC:{value:new THREE.Color('#afb9ab')},uSurfaceMode:{value:5},uAtmoColor:{value:new THREE.Color('#81b4db')},uAtmoStrength:{value:.18},uNightLights:{value:.26},uDim:{value:1},uWaterMask:{value:mask},uMaskMode:{value:mode},uDepth:{value:depth},uCurrent:{value:p.currentMap},uWarm:{value:p.warmMap},uFieldOn:{value:0},uWarmOn:{value:0},uReliefOn:{value:0}}})),[day,cloud,night,mask,depth]);
 const clouds=useMemo(()=>new THREE.ShaderMaterial({vertexShader:cloudVertex,fragmentShader:cloudFragment,transparent:true,depthWrite:false,uniforms:{uMap:{value:cloud},uTime:{value:0},uOpacity:{value:1},sun:{value:SUN_DIRECTION.clone().multiplyScalar(100)}}}),[cloud]);
 useEffect(()=>()=>{materials.forEach(m=>m.dispose());clouds.dispose();},[materials,clouds]);
 useFrame(({camera},dt)=>{const fade=THREE.MathUtils.smoothstep(camera.position.length(),1.008,1.06);if(!p.reducedMotion)clouds.uniforms.uTime.value+=Math.min(dt,.1);clouds.uniforms.uOpacity.value=fade;for(const m of materials){m.uniforms.uHasClouds.value=Number(p.showClouds)*fade;m.uniforms.uTime.value=clouds.uniforms.uTime.value;m.uniforms.uCurrent.value=p.currentMap;m.uniforms.uWarm.value=p.warmMap;m.uniforms.uFieldOn.value=Number(p.showField);m.uniforms.uWarmOn.value=Number(p.geoMode);m.uniforms.uReliefOn.value=Number(p.showSeaRelief);}});
 return <group name="solar-earth-model">{materials.map((m,i)=><mesh key={i} name={i?'ocean-surface':'land-surface'} visible={i?layers.ocean!==false:layers.land!==false} onPointerMove={p.onPointerMove} onPointerOut={p.onPointerOut} onClick={p.onClick}><sphereGeometry args={[p.radius,192,128]}/><primitive object={m} attach="material"/></mesh>)}{p.showClouds&&<mesh name="solar-earth-clouds" scale={1.003} raycast={()=>null}><sphereGeometry args={[p.radius,128,80]}/><primitive object={clouds} attach="material"/></mesh>}</group>;
}
export function clearEarthTextures(){for(const path of TEXTURES)useTexture.clear(path);}
