import {useMemo,useEffect,useRef} from 'react';
import {useFrame} from '@react-three/fiber';
import * as THREE from 'three';
import {useWeather} from '../../lib/weather';
import {sampleWeather,type WeatherGrid} from '../../lib/weatherGrid';
import {useAtlas} from '../../state/store';
function writePoint(out:Float32Array,k:number,lon:number,lat:number){const phi=(lon+180)*Math.PI/180,theta=(90-lat)*Math.PI/180,r=1.00035,s=Math.sin(theta);out[k]=-r*Math.cos(phi)*s;out[k+1]=r*Math.cos(theta);out[k+2]=r*Math.sin(phi)*s;}
const VERT=`varying vec2 vUv;varying vec3 p,n;void main(){vUv=uv;vec4 w=modelMatrix*vec4(position,1.);p=w.xyz;n=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*viewMatrix*w;}`;
const FRAG=`uniform sampler2D field;uniform float mode,lat0,dLat,lon0,dLon;uniform vec2 gridSize;varying vec2 vUv;varying vec3 p,n;
vec3 windColor(float v){if(v<5.)return mix(vec3(.04,.25,.42),vec3(.06,.60,.63),v/5.);if(v<12.)return mix(vec3(.06,.60,.63),vec3(.49,.77,.28),(v-5.)/7.);if(v<22.)return mix(vec3(.49,.77,.28),vec3(.95,.58,.12),(v-12.)/10.);return mix(vec3(.95,.58,.12),vec3(.76,.18,.48),clamp((v-22.)/15.,0.,1.));}
vec3 rainColor(float r){if(r<1.)return mix(vec3(.08,.28,.91),vec3(.02,.85,.93),r);if(r<5.)return mix(vec3(.02,.85,.93),vec3(.32,.85,.2),(r-1.)/4.);if(r<10.)return mix(vec3(.32,.85,.2),vec3(1.,.82,.06),(r-5.)/5.);if(r<20.)return mix(vec3(1.,.82,.06),vec3(1.,.18,.08),(r-10.)/10.);return vec3(.93,.12,.8);}
void main(){if(dot(normalize(n),normalize(cameraPosition-p))<=0.)discard;float lat=vUv.y*180.-90.;if(lat<lat0||lat>lat0+dLat*(gridSize.y-1.))discard;vec2 at=vec2(fract((vUv.x*360.-180.-lon0)/(gridSize.x*dLon)+.5/gridSize.x),((lat-lat0)/dLat+.5)/gridSize.y);vec3 d=texture2D(field,at).rgb;vec2 velocity=(d.rg*2.-1.)*40.;float speed=length(velocity),r=d.b*d.b*30.;vec3 c;float a;if(mode<.5){c=windColor(speed);a=.48;}else{if(r<.05)discard;c=rainColor(r);a=.50+.3*smoothstep(.05,2.,r);}gl_FragColor=vec4(c,a);}`;
function WindStreamlines({grid}:{grid:WeatherGrid}){const ref=useRef<THREE.LineSegments>(null),reduced=useAtlas(s=>s.reducedMotion),quality=useAtlas(s=>s.quality);
 const state=useMemo(()=>{const count=quality==='LOW'?420:quality==='MEDIUM'?800:1400,trail=10,lon=new Float32Array(count),lat=new Float32Array(count),age=new Float32Array(count),positions=new Float32Array(count*trail*6),colors=new Float32Array(positions.length),history=new Float32Array(count*trail*2);for(let i=0;i<count;i++){lon[i]=Math.random()*360-180;lat[i]=Math.asin(Math.random()*1.98-.99)*180/Math.PI;age[i]=Math.random()*20;for(let j=0;j<trail;j++){history[(i*trail+j)*2]=lon[i];history[(i*trail+j)*2+1]=lat[i];}}return {count,trail,lon,lat,age,history,positions,colors,accumulator:0};},[quality,grid]);
 useFrame((_,delta)=>{const dt=reduced?0:Math.min(delta,.05);state.accumulator+=dt;const save=state.accumulator>=.12;if(save)state.accumulator%=.12;for(let i=0;i<state.count;i++){const [u,v]=sampleWeather(grid,state.lon[i],state.lat[i]);state.age[i]+=dt;let lon=state.lon[i]+u*dt*.22/Math.max(.22,Math.cos(state.lat[i]*Math.PI/180)),lat=state.lat[i]+v*dt*.22;const reset=state.age[i]>20||Math.abs(lat)>84;if(reset){lon=Math.random()*360-180;lat=Math.asin(Math.random()*1.98-.99)*180/Math.PI;state.age[i]=0;}lon=((lon+180)%360+360)%360-180;state.lon[i]=lon;state.lat[i]=lat;
 const base=i*state.trail*2;if(save||reset)for(let j=state.trail-1;j>0;j--){state.history[base+j*2]=reset?lon:state.history[base+(j-1)*2];state.history[base+j*2+1]=reset?lat:state.history[base+(j-1)*2+1];}state.history[base]=lon;state.history[base+1]=lat;
 for(let j=0;j<state.trail;j++){const k=(i*state.trail+j)*6,next=Math.min(state.trail-1,j+1);writePoint(state.positions,k,j===0?lon:state.history[base+j*2],j===0?lat:state.history[base+j*2+1]);writePoint(state.positions,k+3,state.history[base+next*2],state.history[base+next*2+1]);const fade=(1-j/state.trail)*Math.min(1,state.age[i]*2);for(let end=0;end<2;end++){const c=k+end*3;state.colors[c]=.68*fade;state.colors[c+1]=.87*fade;state.colors[c+2]=.92*fade;}}}
 if(ref.current){ref.current.geometry.attributes.position.needsUpdate=true;ref.current.geometry.attributes.color.needsUpdate=true;}});
 return <lineSegments ref={ref} frustumCulled={false}><bufferGeometry><bufferAttribute attach="attributes-position" args={[state.positions,3]}/><bufferAttribute attach="attributes-color" args={[state.colors,3]}/></bufferGeometry><lineBasicMaterial vertexColors transparent opacity={.85} blending={THREE.AdditiveBlending} depthWrite={false}/></lineSegments>;
}
export default function WeatherLayer(){const grid=useWeather(s=>s.grid),wind=useAtlas(s=>s.layers.wind),rain=useAtlas(s=>s.layers.rain);
 const texture=useMemo(()=>{if(!grid)return null;const data=new Uint8Array(grid.width*grid.height*4);for(let i=0;i<grid.width*grid.height;i++){data[i*4]=Math.max(0,Math.min(255,(grid.values[i*3]/80+.5)*255));data[i*4+1]=Math.max(0,Math.min(255,(grid.values[i*3+1]/80+.5)*255));data[i*4+2]=Math.max(0,Math.min(255,Math.sqrt(grid.values[i*3+2]/30)*255));data[i*4+3]=255;}const t=new THREE.DataTexture(data,grid.width,grid.height);t.wrapS=THREE.RepeatWrapping;t.magFilter=t.minFilter=THREE.LinearFilter;t.needsUpdate=true;return t;},[grid]);useEffect(()=>()=>texture?.dispose(),[texture]);
 const uniforms=useMemo(()=>grid&&texture?{field:{value:texture},mode:{value:0},lat0:{value:grid.lat0},dLat:{value:grid.dLat},lon0:{value:grid.lon0},dLon:{value:grid.dLon},gridSize:{value:new THREE.Vector2(grid.width,grid.height)}}:null,[grid,texture]);useEffect(()=>{if(uniforms)uniforms.mode.value=rain?1:0;},[rain,uniforms]);
 if(!grid||!texture||!uniforms)return null;
 return <group name="global-weather-field"><mesh raycast={()=>null} scale={1.00018}><sphereGeometry args={[1,192,128]}/><shaderMaterial vertexShader={VERT} fragmentShader={FRAG} uniforms={uniforms} transparent depthWrite={false}/></mesh>{wind&&<WindStreamlines grid={grid}/>}</group>;
}
